src/Entity/OrderItem.php
<?php

namespace App\Entity;

use App\Repository\OrderItemRepository;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: OrderItemRepository::class)]
class OrderItem
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\ManyToOne]
    #[ORM\JoinColumn(nullable: false)]
    private ?Product $product = null;

    #[ORM\Column]
    private ?int $quantity = null;

    #[ORM\ManyToOne(inversedBy: 'items')]
    #[ORM\JoinColumn(nullable: false)]
    private ?Order $orderRef = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getProduct(): ?Product
    {
        return $this->product;
    }

    public function setProduct(?Product $product): self
    {
        $this->product = $product;

        return $this;
    }

    public function getQuantity(): ?int
    {
        return $this->quantity;
    }

    public function setQuantity(int $quantity): self
    {
        $this->quantity = $quantity;

        return $this;
    }

    public function getOrderRef(): ?Order
    {
        return $this->orderRef;
    }

    public function setOrderRef(?Order $orderRef): self
    {
        $this->orderRef = $orderRef;

        return $this;
    }

    /**
     * @param OrderItem $item
     * @return bool
     */
    public function equals(OrderItem $item): bool
    {
        return $this->getProduct()->getId() === $item->getProduct()->getId();
    }
    public function getTotal(): float
    {
        return $this->getProduct()->getPrice() * $this->getQuantity();
    }
}

src/Form/CartType.php
<?php

namespace App\Form;

use App\Entity\Order;
use App\Form\EventListener\ClearCartListener;

use App\Form\EventListener\RemoveCartItemListener;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\CollectionType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class CartType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('items', CollectionType::class, [
                'entry_type' => CartItemType::class,
            ])
            ->add('save', SubmitType::class)
            ->add('clear', SubmitType::class)
        ;
        $builder->addEventSubscriber(new ClearCartListener());
        $builder->addEventSubscriber(new RemoveCartItemListener());
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Order::class,

        ]);
    }
}

src/Controller/CartController.php
<?php

namespace App\Controller;

use App\Form\CartType;
use App\Manager\CartManager;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class CartController extends AbstractController
{
    #[Route('/cart', name: 'app_cart')]
    public function index(CartManager $manager, Request $request): Response
    {
        $user = $this->getUser();
        $cart = $manager->getCurrentCart($user);
        $form = $this->createForm(CartType::class, $cart);

        $form->handleRequest($request);

        if($form->isSubmitted() && $form->isValid()){
            $cart->setUpdatedAt(new \DateTime());
            $manager->save($cart);
            return $this->render('cart/index.html.twig', [
                'cart' => $cart,
                'form' => $form->createView(),
            ]);
        }

        return $this->render('cart/index.html.twig', [
            'cart' => $manager->getCurrentCart($user),
            'form' => $form->createView(),
        ]);
    }
}

templates/cart/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Cart{% endblock %}

{% block body %}
    <div class="card mt-4 p-3">
        <h1>Your Cart</h1>
        {% if cart.items.count > 0 %}
            <div class="row mt-4">
                <!-- List of items -->
                <div class="col-md-8">
                    {{ form_start(form) }}
                    <div class="card">
                        <div class="card-header text-white d-flex" style="background: #a2a99c">
                            <p class="h5 m-0 p-1">Items</p>
                            <div class="ms-auto">
                                {{ form_widget(form.save, {'attr': {'class': 'btn btn-warning'}}) }}
                                {{ form_widget(form.clear, {'attr': {'class': 'btn btn-light'}}) }}
                            </div>
                        </div>
                        <ul class="list-group list-group-flush">
                            {% for item in form.items %}
                                <li class="list-group-item d-flex">
                                    <div class="row">
                                        <div class="col-md-4">
                                            <img src="{{ asset('images/menu_images/'~ item.vars.data.product.id ~'.jpg') }}"
                                                 class="w-100" alt="Product image">
                                        </div>
                                        <div class="col-md-7">
                                            <h5 class="mt-0 mb-0">{{ item.vars.data.product.name }}</h5>
                                            <small>{{ item.vars.data.product.description[:50] }}...</small>
                                            <div class="form-inline mt-2">
                                                <div class="d-flex justify-content-around mb-0 mr-2">
                                                    {{ form_widget(item.quantity, {
                                                        'attr': {
                                                            'class': 'form-control form-control-sm mx-1',
                                                            'min' : '1'
                                                        }
                                                    }) }}
                                                    {{ form_widget(item.remove, {'attr': {'class': 'btn btn-dark btn-sm w-25'}}) }}
                                                    {{ form_rest(item) }}
                                                </div>
                                            </div>
                                        </div>
                                        <div class="col-md-1 text-right">
                                            <b>{{ item.vars.data.product.price }} zł</b>
                                        </div>
                                    </div>
                                </li>
                            {% endfor %}
                        </ul>
                    </div>
                    {{ form_end(form) }}
                </div>
                <!-- Summary -->
                <div class="col-md-4">
                    <div class="card mt-4 mt-md-0">
                        <h5 class="card-header text-white" style="background: #a2a99c">Summary</h5>
                        <ul class="list-group list-group-flush">
                            <li class="list-group-item d-flex justify-content-between">
                                <div><b>Total</b></div>
                                <span><b>{{ cart.total }} zł</b></span>
                            </li>
                        </ul>
                        <div class="card-body">
                            <a href="#" class="btn btn-warning w-100">Checkout</a>
                        </div>
                    </div>
                </div>
            </div>
        {% else %}
            <div class="alert alert-info">
                Your cart is empty. Go to the <a href="{{ path('menu_main') }}">product list</a>.
            </div>
        {% endif %}
    </div>
{% endblock %}